<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Vismaya S D | MSc.Biostatistics | Manipal University" />


<title>Clinical Trial Side-Effects Analysis: A Multilevel Modeling Approach</title>

<script src="Trial-Side-Effects-Analysis_files/header-attrs-2.29/header-attrs.js"></script>
<script src="Trial-Side-Effects-Analysis_files/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="Trial-Side-Effects-Analysis_files/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="Trial-Side-Effects-Analysis_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="Trial-Side-Effects-Analysis_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="Trial-Side-Effects-Analysis_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="Trial-Side-Effects-Analysis_files/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="Trial-Side-Effects-Analysis_files/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="Trial-Side-Effects-Analysis_files/tocify-1.9.1/jquery.tocify.js"></script>
<script src="Trial-Side-Effects-Analysis_files/navigation-1.1/tabsets.js"></script>
<script src="Trial-Side-Effects-Analysis_files/navigation-1.1/codefolding.js"></script>
<link href="Trial-Side-Effects-Analysis_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="Trial-Side-Effects-Analysis_files/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Clinical Trial Side-Effects Analysis: A
Multilevel Modeling Approach</h1>
<h4 class="author">Vismaya S D | MSc.Biostatistics | Manipal
University</h4>
<h4 class="date">08 October, 2025</h4>

</div>


<div id="introduction" class="section level1">
<h1>1. Introduction</h1>
<p>This report details the analysis of simulated data from a
longitudinal clinical trial. The study was designed to assess the side
effects of two different drugs (A and B) over time. The data has a
hierarchical or nested structure: multiple measurements are taken from
each patient over time, and these patients are grouped within different
hospital sites.</p>
<p>The primary goals of this analysis are: 1. To explore the
distribution of side-effect scores and how they change over time for
each drug. 2. To build a statistical model for the continuous
<code>side_effect_score</code> to identify significant predictors and
account for the nested data structure. 3. To build a similar model for a
binary outcome (<code>side_effect_present</code>) and compare the
findings.</p>
</div>
<div id="data-simulation" class="section level1">
<h1>2. Data Simulation</h1>
<p>The data for this analysis was simulated to reflect a realistic
clinical trial scenario.</p>
<ul>
<li><strong>Structure</strong>: 10 hospital sites, with 100 patients per
site, for a total of 1,000 unique patients.</li>
<li><strong>Design</strong>: Each patient was followed for 5 time points
(baseline at time 0, plus 4 follow-ups), resulting in 5,000 total
observations.</li>
<li><strong>Variables</strong>: The key variables include
<code>side_effect_score</code> (a continuous measure from 0-10),
<code>time</code>, <code>drug</code> (A or B), patient <code>age</code>,
<code>sex</code>, and the unique IDs for <code>patient_id</code> and
<code>site_id</code>.</li>
<li><strong>Effects</strong>: The simulation was designed so that Drug B
has more severe side effects than Drug A, and side effects generally
increase over time. It also includes random variation between sites and
between patients.</li>
</ul>
<p><em>The full R code used for the simulation is available by clicking
the ‘Code’ button for the chunk below.</em></p>
</div>
<div id="exploratory-data-analysis-eda" class="section level1">
<h1>3. Exploratory Data Analysis (EDA)</h1>
<p>We begin by visualizing the data to understand its main features.</p>
<pre class="r"><code># Plot 1: Overall distribution of the side-effect score
p1 &lt;- ggplot(data_long, aes(side_effect_score)) +
  geom_histogram(bins = 30, fill = &quot;gray30&quot;, alpha = 0.8) +
  labs(title = &quot;Side-effect score distribution (0-10)&quot;,
       x = &quot;Side Effect Score&quot;, y = &quot;Count&quot;) +
  theme_minimal()

# Plot 2: Mean side-effect score over time by drug
p2 &lt;- data_long %&gt;%
  group_by(time, drug) %&gt;%
  summarise(mean_score = mean(side_effect_score), .groups = &quot;drop&quot;) %&gt;%
  ggplot(aes(time, mean_score, color = drug, group = drug)) +
  geom_line(linewidth = 1) + 
  geom_point(size = 3) +
  labs(title = &quot;Mean side-effect score by time and drug&quot;,
       x = &quot;Time&quot;, y = &quot;Mean Side Effect Score&quot;, color = &quot;Drug&quot;) +
  theme_minimal()

# Display plots side-by-side
p1 + p2</code></pre>
<p><img src="Trial-Side-Effects-Analysis_files/figure-html/eda-plots-1.png" width="672" /></p>
<div id="interpretation" class="section level3">
<h3>Interpretation</h3>
<ul>
<li><p><strong>Graph 1: Histogram (Left)</strong>: This plot shows the
overall distribution of the <code>side_effect_score</code>. The most
frequent scores are between 2.0 and 4.0, with a peak around 2.5. The
distribution is skewed to the right, indicating that while most scores
are low, a smaller number of higher scores exist. Very high scores
(above 7.5) are rare.</p></li>
<li><p><strong>Graph 2: Line Plot (Right)</strong>: This plot shows how
the average side-effect score changes over time for Drugs A and B.</p>
<ul>
<li><strong>Effect of Drug</strong>: The blue line (Drug B) is
consistently higher than the red line (Drug A) at all time points. This
provides strong visual evidence that patients on Drug B report more
severe side effects on average.</li>
<li><strong>Effect of Time</strong>: Both lines trend upwards. This
indicates that for both drugs, the average severity of side effects
increases over the course of the study.</li>
</ul></li>
</ul>
</div>
</div>
<div id="analysis-of-continuous-outcome-side_effect_score"
class="section level1">
<h1>4. Analysis of Continuous Outcome
(<code>side_effect_score</code>)</h1>
<p>To properly analyze this data, we use a <strong>three-level linear
mixed-effects model</strong>. This type of model is ideal because it can
handle the nested structure of the data: measurements are nested within
patients, who are in turn nested within sites. This allows us to account
for the fact that observations from the same patient (or the same site)
are likely to be more similar to each other than to observations from
other patients or sites.</p>
<div id="model-1-random-intercepts-for-patient-and-site"
class="section level3">
<h3>4.1 Model 1: Random Intercepts for Patient and Site</h3>
<p>Our first model includes <code>time</code>, <code>drug</code>,
<code>dose</code>, <code>age</code>, and <code>sex</code> as fixed
effects. It also includes random intercepts for <code>site_id</code> and
<code>patient_id</code>. This accounts for baseline differences in
side-effect scores across different sites and patients.</p>
<pre class="r"><code>model1 &lt;- lmer(side_effect_score ~ time + drug + dose + age + sex + 
                 (1 | site_id) + (1 | patient_id),
               data = data_long, REML = TRUE)</code></pre>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Table 1: Results of Three-Level Random Intercept Model (model1)
</caption>
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="6" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
side effect score
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
std. Error
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Statistic
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  col7">
df
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.61
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.21
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.20 – 2.03
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
7.60
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
4991.00
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
time
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.21
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.19 – 0.24
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
18.20
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
4991.00
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
drug [B]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.82
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.20
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.43 – 1.21
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
4.09
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
4991.00
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
dose
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.00
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.01 – 0.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.29
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.770
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
4991.00
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
age
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.00
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.00 – 0.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
2.75
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>0.006</strong>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
4991.00
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
sex
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.19
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.05
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.10 – 0.29
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
3.86
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  col7">
4991.00
</td>
</tr>
<tr>
<td colspan="7" style="font-weight:bold; text-align:left; padding-top:.8em;">
Random Effects
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
σ<sup>2</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="6">
1.36
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
τ<sub>00</sub> <sub>patient_id</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="6">
0.34
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
τ<sub>00</sub> <sub>site_id</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="6">
0.17
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
ICC
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="6">
0.27
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
N <sub>site_id</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="6">
10
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
N <sub>patient_id</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="6">
1000
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="6">
5000
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
Marginal R<sup>2</sup> / Conditional R<sup>2</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="6">
0.135 / 0.372
</td>
</tr>
</table>
</div>
<div id="interpretation-of-model-1-results" class="section level3">
<h3>Interpretation of Model 1 Results</h3>
<ul>
<li><strong>Fixed Effects</strong>:
<ul>
<li><code>time</code>: For each one-unit increase in time, the
side-effect score increases by an average of 0.21 points (p &lt; .001).
This is a highly significant effect.</li>
<li><code>drugB</code>: Patients on Drug B have side-effect scores that
are, on average, 0.82 points higher than those on Drug A (p &lt; .001),
after controlling for other factors.</li>
<li><code>age</code>: For each additional year of age, the score
increases by a very small but significant 0.006 points (p = 0.006).</li>
<li><code>sex</code>: Females (coded as 1) report scores that are 0.19
points higher on average than males (p &lt; .001).</li>
<li><code>dose</code>: The effect of dose was not statistically
significant (p = 0.77).</li>
</ul></li>
<li><strong>Random Effects</strong>:
<ul>
<li>The model estimates significant variance at both the
<code>site_id</code> level (Var = 0.17) and the <code>patient_id</code>
level (Var = 0.34). This confirms that there are meaningful baseline
differences in side-effect scores among both sites and individual
patients, justifying the use of a mixed-effects model.</li>
</ul></li>
</ul>
</div>
<div id="model-2-adding-a-random-slope-for-time" class="section level3">
<h3>4.2 Model 2: Adding a Random Slope for Time</h3>
<p>We can extend the model to see if the effect of time is different for
each patient. This is done by adding a <strong>random slope</strong> for
<code>time</code> at the patient level.</p>
<pre class="r"><code>model2 &lt;- lmer(side_effect_score ~ time + drug + dose + age + sex + 
                 (1 | site_id) + (1 + time | patient_id),
               data = data_long, REML = TRUE)</code></pre>
<p>When fitting this model, a warning message appears:
<code>boundary (singular) fit</code>. This is an important diagnostic.
It suggests that the model is too complex for the data and that the
random slope for time is not needed. The variance of the time slope is
estimated to be nearly zero.</p>
</div>
<div id="model-comparison-and-conclusion" class="section level3">
<h3>4.3 Model Comparison and Conclusion</h3>
<p>Comparing <code>model1</code> and <code>model2</code>, we see that
the fixed effect estimates are nearly identical. The singular fit
warning in <code>model2</code> indicates that it is overfitted. The data
does not support the complex idea that every patient has a unique
trajectory over time.</p>
<p>✅ <strong>Conclusion</strong>: The simpler random-intercept model
(<code>model1</code>) is the more reliable and appropriate choice for
this analysis.</p>
</div>
<div id="testing-the-significance-of-random-effects"
class="section level3">
<h3>4.4 Testing the Significance of Random Effects</h3>
<p>We can formally test if the random effects for <code>site_id</code>
and <code>patient_id</code> are statistically necessary using a
Likelihood Ratio Test (LRT).</p>
<pre class="r"><code># 1. Refit model1 using Maximum Likelihood (ML)
model1_ml &lt;- lmer(side_effect_score ~ time + drug + dose + age + sex + 
                    (1 | site_id) + (1 | patient_id),
                  data = data_long, REML = FALSE)

# 2. Fit a model without the site_id random effect
model_no_site &lt;- lmer(side_effect_score ~ time + drug + dose + age + sex + 
                        (1 | patient_id),
                      data = data_long, REML = FALSE)

# 3. Fit a model without the patient_id random effect
model_no_patient &lt;- lmer(side_effect_score ~ time + drug + dose + age + sex + 
                           (1 | site_id),
                         data = data_long, REML = FALSE)

# 4. Compare models
cat(&quot;--- Test for site_id ---\n&quot;)</code></pre>
<pre><code>## --- Test for site_id ---</code></pre>
<pre class="r"><code>anova(model_no_site, model1_ml)</code></pre>
<pre><code>## Data: data_long
## Models:
## model_no_site: side_effect_score ~ time + drug + dose + age + sex + (1 | patient_id)
## model1_ml: side_effect_score ~ time + drug + dose + age + sex + (1 | site_id) + (1 | patient_id)
##               npar   AIC   BIC  logLik -2*log(L)  Chisq Df Pr(&gt;Chisq)    
## model_no_site    8 16777 16829 -8380.5     16761                         
## model1_ml        9 16586 16645 -8284.1     16568 192.82  1  &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>cat(&quot;\n--- Test for patient_id ---\n&quot;)</code></pre>
<pre><code>## 
## --- Test for patient_id ---</code></pre>
<pre class="r"><code>anova(model_no_patient, model1_ml)</code></pre>
<pre><code>## Data: data_long
## Models:
## model_no_patient: side_effect_score ~ time + drug + dose + age + sex + (1 | site_id)
## model1_ml: side_effect_score ~ time + drug + dose + age + sex + (1 | site_id) + (1 | patient_id)
##                  npar   AIC   BIC  logLik -2*log(L) Chisq Df Pr(&gt;Chisq)    
## model_no_patient    8 16884 16936 -8434.1     16868                        
## model1_ml           9 16586 16645 -8284.1     16568 300.1  1  &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Both tests yield a p-value of <code>&lt; 2.2e-16</code>, providing
overwhelming evidence that including random intercepts for both site and
patient significantly improves the model fit.</p>
</div>
<div id="intraclass-correlation-coefficient-icc" class="section level3">
<h3>4.5 Intraclass Correlation Coefficient (ICC)</h3>
<p>The ICC tells us what proportion of the total variance in side-effect
scores is attributable to differences between sites and between
patients.</p>
<pre class="r"><code>vc &lt;- as.data.frame(VarCorr(model1))
sigma_site &lt;- vc$vcov[vc$grp == &quot;site_id&quot;]
sigma_patient &lt;- vc$vcov[vc$grp == &quot;patient_id&quot;]
sigma_resid &lt;- attr(VarCorr(model1), &quot;sc&quot;)^2

icc_site &lt;- sigma_site / (sigma_site + sigma_patient + sigma_resid)
icc_patient &lt;- sigma_patient / (sigma_site + sigma_patient + sigma_resid)

icc_df &lt;- data.frame(
  Level = c(&quot;Site (Between-Sites)&quot;, &quot;Patient (Between-Patients)&quot;),
  ICC = c(icc_site, icc_patient),
  `Percent of Variance` = scales::percent(c(icc_site, icc_patient), accuracy = 0.1)
)

kable(icc_df, caption = &quot;Table 2: Intraclass Correlation Coefficients (ICCs)&quot;)</code></pre>
<table>
<caption>Table 2: Intraclass Correlation Coefficients (ICCs)</caption>
<thead>
<tr class="header">
<th align="left">Level</th>
<th align="right">ICC</th>
<th align="left">Percent.of.Variance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Site (Between-Sites)</td>
<td align="right">0.0921727</td>
<td align="left">9.2%</td>
</tr>
<tr class="even">
<td align="left">Patient (Between-Patients)</td>
<td align="right">0.1817149</td>
<td align="left">18.2%</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>ICC for Site</strong>: About <strong>9.2%</strong> of the
total variation in side-effect scores can be attributed to systematic
differences between the hospital sites.</li>
<li><strong>ICC for Patient</strong>: About <strong>18.2%</strong> of
the total variation is due to stable, consistent differences between the
individual patients.</li>
</ul>
<p>Together, the nested structure (sites and patients) accounts for over
27% of the total variability in the data, confirming that our
mixed-effects modeling approach was essential.</p>
</div>
</div>
<div id="analysis-of-binary-outcome-side_effect_present"
class="section level1">
<h1>5. Analysis of Binary Outcome
(<code>side_effect_present</code>)</h1>
<p>Next, we analyze a binary version of the outcome: whether a side
effect was present (1) or absent (0). For this, we use a
<strong>generalized linear mixed-effects model</strong>
(<code>glmer</code>) with a binomial family.</p>
<pre class="r"><code>model_bin &lt;- glmer(side_effect_present ~ time + drug + dose + age + sex + 
                     (1 | site_id) + (1 | patient_id),
                   data = data_long, family = binomial(link = &quot;logit&quot;),
                   control = glmerControl(optimizer = &quot;bobyqa&quot;, optCtrl = list(maxfun = 2e5)))</code></pre>
<table style="border-collapse:collapse; border:none;">
<caption style="font-weight: bold; text-align:left;">
Table 3: Results of Three-Level Binary Logistic Model (model_bin)
</caption>
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="5" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
side effect present
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Odds Ratios
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
std. Error
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Statistic
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.48
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.10
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.32 – 0.71
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-3.64
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
time
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.13
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.02
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.08 – 1.17
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
5.89
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001</strong>
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
drug [B]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.09
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.25
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.69 – 1.72
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.36
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.716
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
dose
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.99 – 1.02
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.312
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
age
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.00
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.00
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.00 – 1.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.69
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.493
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
sex
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.08
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.06
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.96 – 1.21
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
1.23
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.217
</td>
</tr>
<tr>
<td colspan="6" style="font-weight:bold; text-align:left; padding-top:.8em;">
Random Effects
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
σ<sup>2</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="5">
3.29
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
τ<sub>00</sub> <sub>patient_id</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="5">
0.02
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
τ<sub>00</sub> <sub>site_id</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="5">
0.02
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
ICC
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="5">
0.01
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
N <sub>site_id</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="5">
10
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
N <sub>patient_id</sub>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="5">
1000
</td>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="5">
5000
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
Marginal R<sup>2</sup> / Conditional R<sup>2</sup>
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="5">
0.016 / 0.030
</td>
</tr>
</table>
<div id="interpretation-of-binary-model-results" class="section level3">
<h3>Interpretation of Binary Model Results</h3>
<ul>
<li><p><strong>Convergence Warnings</strong>: The model produced
warnings about failing to converge and being “nearly unidentifiable.”
This is a major red flag, indicating that the model is likely too
complex for the binary data and its results may not be
reliable.</p></li>
<li><p><strong>Fixed Effects (as Odds Ratios)</strong>:</p>
<ul>
<li><code>time</code>: For each one-unit increase in time, the odds of a
side effect being present increase by about 13% (Odds Ratio [OR] = 1.13,
p &lt; .001). This is the only significant predictor.</li>
<li><code>drugB</code>, <code>dose</code>, <code>age</code>,
<code>sex</code>: None of these predictors were statistically
significant. Their odds ratios are all very close to 1, suggesting they
have little to no effect on the <em>probability</em> of a side effect
occurring.</li>
</ul></li>
</ul>
</div>
<div id="variance-components-for-the-binary-model"
class="section level3">
<h3>Variance Components for the Binary Model</h3>
<p>For binary models, we use the <strong>Median Odds Ratio
(MOR)</strong> instead of the ICC to interpret the magnitude of
clustering. The MOR translates the variance at a given level into an
odds ratio, making it easier to interpret. An MOR of 1.0 means there is
no variation between clusters.</p>
<pre class="r"><code># Extract variance components
vc_bin &lt;- as.data.frame(VarCorr(model_bin))
var_site &lt;- vc_bin$vcov[vc_bin$grp == &quot;site_id&quot;]
var_patient &lt;- vc_bin$vcov[vc_bin$grp == &quot;patient_id&quot;]

# Calculate MOR
mor_site &lt;- exp(sqrt(2 * var_site) * qnorm(0.75))
mor_patient &lt;- exp(sqrt(2 * var_patient) * qnorm(0.75))

# Display results
mor_df &lt;- data.frame(
  Level = c(&quot;Site&quot;, &quot;Patient&quot;),
  MOR = c(mor_site, mor_patient)
)
kable(mor_df, caption = &quot;Table 4: Median Odds Ratios (MORs) for Binary Model&quot;, digits=2)</code></pre>
<table>
<caption>Table 4: Median Odds Ratios (MORs) for Binary Model</caption>
<thead>
<tr class="header">
<th align="left">Level</th>
<th align="right">MOR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Site</td>
<td align="right">1.16</td>
</tr>
<tr class="even">
<td align="left">Patient</td>
<td align="right">1.15</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>MOR for Site = 1.16</strong>: If you randomly picked one
patient from a high-risk site and another from a low-risk site, the
patient from the high-risk site would have, on average, 1.16 times the
odds of having a side effect. This is a very small effect, close to
1.0.</li>
<li><strong>MOR for Patient = 1.15</strong>: Similarly, the variation
between individual patients is also very small.</li>
</ul>
<p>These MOR values suggest that clustering by site and patient has a
negligible impact on the binary outcome.</p>
</div>
</div>
<div id="final-conclusion" class="section level1">
<h1>6. Final Conclusion</h1>
<p>This analysis provides a clear picture of the simulated clinical
trial data.</p>
<ol style="list-style-type: decimal">
<li><p><strong>Continuous Score is More Informative</strong>: The
analysis of the continuous <code>side_effect_score</code> was highly
informative. The mixed-effects model (<code>model1</code>) fit the data
well and showed significant effects for <code>time</code>,
<code>drug</code>, <code>age</code>, and <code>sex</code>. It also
confirmed that accounting for the data’s nested structure was crucial,
as over 27% of the score’s variance was explained by differences between
sites and patients.</p></li>
<li><p><strong>Binary Outcome Loses Information</strong>: In contrast,
the analysis of the binary <code>side_effect_present</code> variable was
problematic. The model struggled to converge, suggesting it was
unstable. It found that only <code>time</code> was a significant
predictor, and the effects of clustering (by site and patient) were
negligible. Dichotomizing a continuous outcome into a binary one
resulted in a significant loss of statistical power and
information.</p></li>
</ol>
<p>In summary, for this dataset, the continuous side-effect score
provides a much richer and more reliable understanding of the treatment
effects than its binary counterpart. The final recommendation would be
to use the results from <strong>Model 1</strong> for any conclusions or
further research.</p>
<div id="session-information" class="section level2">
<h2>Session Information</h2>
<p>The following details show the R version and package versions used to
generate this report, ensuring reproducibility.</p>
<pre><code>## R version 4.4.1 (2024-06-14 ucrt)
## Platform: x86_64-w64-mingw32/x64
## Running under: Windows 11 x64 (build 26100)
## 
## Matrix products: default
## 
## 
## locale:
## [1] LC_COLLATE=English_India.utf8  LC_CTYPE=English_India.utf8   
## [3] LC_MONETARY=English_India.utf8 LC_NUMERIC=C                  
## [5] LC_TIME=English_India.utf8    
## 
## time zone: Asia/Calcutta
## tzcode source: internal
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
##  [1] knitr_1.49      patchwork_1.3.0 sjPlot_2.9.0    lmerTest_3.1-3 
##  [5] lme4_1.1-37     Matrix_1.7-0    lubridate_1.9.4 forcats_1.0.0  
##  [9] stringr_1.5.1   dplyr_1.1.4     purrr_1.0.2     readr_2.1.5    
## [13] tidyr_1.3.1     tibble_3.2.1    ggplot2_3.5.1   tidyverse_2.0.0
## 
## loaded via a namespace (and not attached):
##  [1] gtable_0.3.6        xfun_0.50           bslib_0.8.0        
##  [4] bayestestR_0.17.0   insight_1.4.2       lattice_0.22-6     
##  [7] tzdb_0.4.0          numDeriv_2016.8-1.1 vctrs_0.6.5        
## [10] tools_4.4.1         Rdpack_2.6.2        generics_0.1.3     
## [13] sandwich_3.1-1      datawizard_1.2.0    pkgconfig_2.0.3    
## [16] RColorBrewer_1.1-3  lifecycle_1.0.4     compiler_4.4.1     
## [19] farver_2.1.2        sjmisc_2.8.11       codetools_0.2-20   
## [22] snakecase_0.11.1    htmltools_0.5.8.1   sass_0.4.9         
## [25] yaml_2.3.10         pillar_1.10.1       nloptr_2.1.1       
## [28] jquerylib_0.1.4     MASS_7.3-65         cachem_1.1.0       
## [31] reformulas_0.4.1    multcomp_1.4-26     boot_1.3-32        
## [34] nlme_3.1-164        tidyselect_1.2.1    sjlabelled_1.2.0   
## [37] digest_0.6.37       performance_0.15.1  mvtnorm_1.3-3      
## [40] stringi_1.8.4       labeling_0.4.3      splines_4.4.1      
## [43] fastmap_1.2.0       grid_4.4.1          cli_3.6.3          
## [46] magrittr_2.0.3      survival_3.8-3      TH.data_1.1-3      
## [49] withr_3.0.2         scales_1.4.0        timechange_0.3.0   
## [52] estimability_1.5.1  rmarkdown_2.29      emmeans_1.10.7     
## [55] zoo_1.8-12          hms_1.1.3           coda_0.19-4.1      
## [58] evaluate_1.0.3      parameters_0.28.1   rbibutils_2.3      
## [61] rlang_1.1.5         Rcpp_1.0.14         xtable_1.8-4       
## [64] glue_1.8.0          effectsize_1.0.1    rstudioapi_0.17.1  
## [67] minqa_1.2.8         jsonlite_1.8.9      R6_2.5.1</code></pre>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
